@startuml class

skinparam classAttributeIconSize 0

class User {
  #id: int
  #nom: string
  #email: string
  #motDePasse: string
  +register()
  +login()
  +logout()
}

class volunteer {
  -participatioHistory: list
  +achievementSation()
}

class Organization {
  -publishedOpportunities: list
  +OpportunityManagement()
}

class Admin {
  +Usermanagement()
  +superviserOpportunitys()
  +analyserStatistics()
  +contentModeration()
}

class Opportunity {
  -id: int
  -titre: string
  -description: string
  -localisation: string
  -durée: string
  +createOpportunity()
  +editOpportunity()
  +deleteOpportunity()
}

class Candidature {
  -id: int
  -statut: string
  -dateSoumission: date
  +postuler()
  +accept()
  +refuse()
}

class Statistics {
  -nombrevolunteers: int
  -nombreOpportunitys: int
  +generateRapport()
}

class Message {
  -id: int
  -contenu: string
  +sendMessage()
}

class Donation {
  -id: int
  -description: string
  -état: string
  +postDonation()
  +editDonation()
  +deleteDonation()
}

User <|-- volunteer
User <|-- Organization
User <|-- Admin
User --> Message 

volunteer --* Donation 
volunteer --> Candidature
volunteer --> Opportunity 

Organization --> Opportunity
Organization --> Statistics 
Organization --* Donation 

Admin --> Statistics  
Admin --> Opportunity 

Candidature --> Opportunity

@enduml
